---
- name: add/upgrade EPEL repository
  package:
    state: latest
    name: epel-release
  when: ansible_facts['distribution'] == "CentOS"

- name: install base EPEL packages
  package:
    state: present
    name:
      - certbot
