---
- name: create game server system user
  user:
    name: games-admin
    comment: "system user to run processes for game servers - do not use"
    create_home: no
    home: /var/lib/games
    system: yes

- name: append games-admin group to admin users
  user:
    name: "{{ item }}"
    groups: games-admin
    append: yes
  loop: "{{ games_admin_users }}"
