---
# tasks file for user-management
- name: verify all admin UIDs exist and use a bash shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/bash
  loop: "{{ admin_uids }}"

- name: install custom sudoers.d file for %spigot-admins to administer system
  copy:
    src: 10_spigot-admin
    dest: /etc/sudoers.d/10_spigot-admin
    mode: 0640
    setype: etc_t
    seuser: system_u
    validate: /usr/sbin/visudo --check --strict --file=%s
