---
- name: synchronize Anvil
  hosts: anvil.ccmc.pw
  become: yes

  roles:
    - { role: system/firewalld, tags: ['firewalld', 'system'] }
    - { role: system/selinux, tags: ['selinux', 'system'] }
    # - { role: system/sshd, tags: ['sshd', 'system'] }
    - { role: anvil.ccmc.pw, tags: ['anvil', 'apps'] }
