---
- name: fire up the Anvil
  hosts: anvil
  become: yes

  roles:
    - { role: system/firewalld, tags: ['firewalld', 'system'] }
    - { role: system/selinux, tags: ['selinux', 'system'] }
    - { role: system/sshd, tags: ['sshd', 'system'] }
    - { role: system/user-management, tags: ['users', 'user-management', 'system'] }
    - { role: anvil.ccmc.pw, tags: ['anvil', 'apps'] }
    - { role: spigot, tags: ['spigot', 'minecraft', 'apps'] }
